import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from "wagmi";
import { config } from "./blockchain/Config/config";
import { headers } from "next/headers";
import Web3ModalProvider from "./Components/Providers";
import Sidebar from "./Components/Sidebar";
// import CampaignContextProvider from "./Context/CampaignContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <html lang="en">
      <body className={inter.className}><Web3ModalProvider initialState={initialState}>
        <div className="bg-[#14121B] h-full flex items-start gap-20 px-8 ">
        <Sidebar/>
       
        {children}
        
        </div>
        </Web3ModalProvider></body>
    </html>
  );
}
